### PR TITLE
Support `https` in `$schema`

### PR DESCRIPTION
**Pull request by WillDaSilva**

### CODE REVIEW

**Comment by sirosen** [comment]
Could you explain your use-case a bit so that I know why you want this change?

I was only just looking at this and thinking that it might be better to use `validator_for({"$schema": schema_dialect})`. Without any further context, I'm not sure whether or not your use-case is going to be resolved by that.

I also am not sure it is safe -- actually, I'm pretty sure it is unsafe -- to blanket modify `$schema` values. Someone could have a custom metaschema, a case which I think is already not handled well, and that's one of the things I'd like to fix.

**Comment by sirosen** [comment]
After thinking about it a little more, I'm going to close this. The PR doesn't really stand any chance at being accepted (breaks on newer metaschemas), so leaving it open just makes that unclear.

A better avenue for discussion is to open an issue and describe your use-case.

**Comment by WillDaSilva** [comment]
@sirosen For context, the code I changed only pertains to looking up a schema in this dictionary at the top of the file:

```python
CHECKERS_BY_DIALECT = {
    "http://json-schema.org/draft-03/schema#": jsonschema.Draft3Validator.FORMAT_CHECKER,
    "http://json-schema.org/draft-04/schema#": jsonschema.Draft4Validator.FORMAT_CHECKER,
    "http://json-schema.org/draft-06/schema#": jsonschema.Draft6Validator.FORMAT_CHECKER,
    "http://json-schema.org/draft-07/schema#": jsonschema.Draft7Validator.FORMAT_CHECKER,
    "http://json-schema.org/draft-2019-09/schema": (
        jsonschema.Draft201909Validator.FORMAT_CHECKER
    ),
    "http://json-schema.org/draft-2020-12/schema": (
        jsonschema.Draft202012Validator.FORMAT_CHECKER
    ),
}
```

JSONschema now recommends using `https` instead of `http` for the value of `$schema` when it is one of the draft releases listed above. The dictionary `CHECKERS_BY_DIALECT` assumes that only `http` will be used, and so it does not function properly when the official advice from JSONschema is followed.

The change in this PR merely makes it so that when getting a format checker from the above dictionary, `https` links to versions on `json-schema.org` map to the same values as the `http` links.

**Comment by sirosen** [comment]
Okay, that makes sense.

If I'm reading this right -- I'll have to come back to it after my workday -- I introduced a bug when putting that dict in place. I still think that a better fix would be to use `validator_for` to do the lookup, which I'll try to incorporate as part of the bugfix branch I have right now for another, related, issue.

**Comment by WillDaSilva** [comment]
> I'll try to incorporate as part of the bugfix branch I have right now for another, related, issue.

Sounds good. Thank you very much @sirosen!

**Pull request closed without merging**
