### PR TITLE
Feature/add vendor bitbucket pipelines

### PR DESCRIPTION
**Pull request by djgoku**

### CODE REVIEW

**Comment by sirosen** [comment]
Hi, thanks for submitting this!

The CI issues aren't related to your work -- some dependency updates have put us in a bad state in which `main` fails CI right now. I'll try to make time in the next few days to fix this, and then we can get CI passing on this and merge it.

(In terms of your work here, no notes! It looks good. But I want the confirmation from CI that I'm not missing anything.)

**Comment by djgoku** [comment]
Thank you for the review!

Is there anything I can possibly help with?

**Comment by sirosen** [comment]
I appreciate the offer. In this case, I think you've already provided the most important thing, which is energy and attention put into the project! I've already put together a patch to get CI back in working shape and merged it (https://github.com/python-jsonschema/check-jsonschema/pull/284).

Would you be willing to rebase to pick up those fixes?

**Comment by djgoku** [comment]
> Would you be willing to rebase to pick up those fixes?

Done!

**Pull request merged**
