### PR TITLE
Enable checking .renovaterc.json5 files with pre-commit hook

### PR DESCRIPTION
**Pull request by tpansino**
Adjust pre-commit hook file regex to allow for `.json5` extensions, as these are [valid](https://docs.renovatebot.com/configuration-options/#configuration-options) for `.renovaterc` config files.

### CODE REVIEW

**Comment by sirosen** [comment]
`.renovaterc` also needs to be supported as a filename, which is why CI is failing on the modified regex.

I suggest splitting `.renovaterc` and `.renovaterc.(json|json5)` into separate lines in the pattern. That also removes any need for the `?`, since `.renovaterc.` is not a valid pattern.

Thanks for the contribution!

**Comment by tpansino** [comment]
My apologies, I should have caught that.

**Comment by sirosen** [comment]
I made a minor change to reflect the new regex in the catalog (which is used to generate the hook config), and this is good to go. I'll make sure to add credit in the changelog for you as well. Thanks again!

**Comment by tpansino** [comment]
Thank you for being so prompt and making the contribution process easy!

**Pull request merged**
