### PR TITLE
Add Woodpecker-CI schema

### PR DESCRIPTION
**Pull request by 6543**
add schema for https://woodpecker-ci.org

### CODE REVIEW

**Comment by 6543** [comment]
ci rerun ?!?

**Comment by sirosen** [comment]
Thanks for contributing this! I'm pretty much always happy to expand the vocabulary of hooks and schemas to serve more folks.

Everything looks to be in order here. I might want to look at the Woodpecker docs to grab a test case or two, just to make sure that this doesn't get broken in the future.

I'm a bit swamped at work, but I'll try to do a release soon to get this out and into people's hands!

**Comment by 6543** [comment]
we have official test assets, witch we ourselve test against:

 - [files](https://github.com/woodpecker-ci/woodpecker/tree/main/pipeline/frontend/yaml/linter/schema/.woodpecker)
 - [actual test](https://github.com/woodpecker-ci/woodpecker/blob/main/pipeline/frontend/yaml/linter/schema/schema_test.go) ([fail example](https://github.com/woodpecker-ci/woodpecker/blob/8c63c7a836ff6013c9d46cb4a7acf1fc525a47ae/pipeline/frontend/yaml/linter/schema/schema_test.go#L110-L112); [success example](https://github.com/woodpecker-ci/woodpecker/blob/8c63c7a836ff6013c9d46cb4a7acf1fc525a47ae/pipeline/frontend/yaml/linter/schema/schema_test.go#L96-L97))

**Comment by sirosen** [comment]
I pulled one of the success cases and included the woodpecker-ci license data in a header, and I added my own failure case.

I've just released this as part of v0.27.4!
Let me know if you see any issues using it, or have other updates to send my way. :+1:

**Comment by 6543** [comment]
Wow thanks :)

**Pull request merged**
