### PR TITLE
Add latest macOS runners

### PR DESCRIPTION
**Pull request by philipphofmann**
Add more macOS runners as pointed out at the GH actions docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners.

### CODE REVIEW

**Comment by sirosen** [comment]
At first I thought this was an update to the github workflow _for this repo_, so I hit the run button.

The schema is actually vendored and sourced from [SchemaStore](https://github.com/SchemaStore/schemastore), so this change will just be overridden.
We can use this as a thread to discuss further how you should make a change over there, but this is not going to merge.

**Comment by philipphofmann** [comment]
I opened a PR https://github.com/SchemaStore/schemastore/pull/2979. Let's see how it goes.

**Comment by sirosen** [comment]
:crossed_fingers: that it goes smoothly.

There's a daily update job here which does PRs with the newly vendored schemas, so ~1 day after your changes merge, I can do a release to bundle the new schema. I generally do it when I am otherwise working on check-jsonschema or if it's been a long time, but I'm always happy to do it on-demand to get new schemas out, so feel free to ping me if you ever need it.

(I have a project to make the updates completely automated, but I haven't had time to work on it.)

**Comment by philipphofmann** [comment]
Thanks for the update 👍 , @sirosen. 

> (I have a project to make the updates completely automated, but I haven't had time to work on it.)

I totally get that 😄.

**Comment by philipphofmann** [comment]
@sirosen, the PR is merged https://github.com/SchemaStore/schemastore/pull/2979. You can do a new release if you want 😃.

**Comment by sirosen** [comment]
I've just done a release of v0.23.1 with the updated vendored schemas. Please let me know if you see any issues with it! :slightly_smiling_face:

**Comment by philipphofmann** [comment]
Thanks @sirosen 🥇

**Pull request closed without merging**
